Codegen Changes -- f string based display
OpenNyAI/Jugalbandi-Studio-Engine pull request #19
Opened 2024-07-10 17:20 UTC by kanak8278

* added f string based display
* handling for error_goto in input task
* Check if there is no variable in fsm, then pydantic variable class should have just pass

2024-07-10 19:26 UTC, vageesh requested changes

2024-07-10 19:26 UTC, vageesh commented on app/utils/codegen.py
> +        pydantic_code = "\n".join(["    " + l for l in pydantic_code.split("\n")])
this indentation is not needed

2024-07-11 05:10 UTC, sameersegal approved these changes

2024-07-11 05:13 UTC, sameersegal commented
@vageesh can you explain why you are using `ast` package.

2024-07-15 05:59 UTC, vageesh approved these changes

2024-07-15 06:05 UTC, sameersegal approved these changes

2024-07-15 06:05 UTC, merged